
INSERT INTO `areas` VALUES 
('K','Area K was surveyed in 2012 and several features were excavated in the 2013, 2014, and 2015 excavation seasons. A large winery complex with a treading floor, two vats, and other rock-cut features was cleared in 2013 and a MBIIC shaft tomb was excavated in 2014.','Area Supervisors (2013): Deborah Appler and Philippe Guillaume\nArea Registrar (2013): Kelly Goodner\nArea Supervisor (2014): Philippe Guillaume'),
('L','Area L was surveyed in 2012 and a trench was opened during the 2016 excavation season in order to identify evidence of the road that led from the valley to the Iron Age gate on Tel Jezreel.','Area Supervisor: Inbal Samet'),
('M','Area M was surveyed in 2012 and excavated for two weeks in 2013. Several bedrock features on a promontory on the northern edge of Tel Jezreel were explored.','Area Supervisors: Deborah Appler and Philippe Guillaume\nArea Registrar: Kelly Goodner'),
('N','Area N was surveyed in 2012. It corresponds to the remains of the Palestinian village Zer\'in.','There were no excavations in Area N 2013-2018.'),
('P','Area P was surveyed in June 2012 and excavated in December 2012 and May-June 2013. Excavations in December 2012 focused on square building of unknown date on a promontory within sight of Ain Jalut (Ein Harod) in the valley below and to the east. In 2013, several trenches were opened to explore the paths that connected Tel Jezreel to the spring below from the Roman period through the 20th century CE.','Area Supervisors: Rafi Lewis and Philippe Guillaume'),
('Q','Area Q was surveyed in 2012 and several areas were chosen for excavation in 2016. A large MB (?) shaft tomb and the area around it was explored in 2016 along with an olive pressing installation.','Area Supervisor: Philippe Guillaume\nArea Registrar: Emily Stewart'),
('S','Area S was the main excavation area in the 2013-2018 seasons. It corresponds to Tel Ein Jezreel, a newly-identified site located adjacent to Ein Jezreel (the spring). Excavation squares were opened in the eastern part of the uncultivated area in 2013 and excavations focused the highest part of the area at the top of a path leading down to the spring during the 2014-2018 field seasons. While this site seems to have reached its greatest extent in the Early Bronze Age, it was settled from as early as Late Neolithic Period and sporadically in later periods.','Field Director: Ian Cipin\nArea Supervisors (all seasons): Deborah Appler, Julye Bidmead, Noga Blockman, Ian Cipin, Inbal Samet\nRegistrars: Judith Hadley (2013-2014) and Ann Stehney (2015-2018)');
INSERT INTO `seasons` VALUES 
('2','In February 2012, the Jezreel Expedition team commissioned a LiDAR (Light Detection and Ranging) airborne laser scan of ca. 7.5 square kilometers of greater Jezreel; it was the first time aerial LiDAR was used by an archaeological project in Israel. The LiDAR scan provided us with accurate locational and height data that enabled the creation of a three-dimensional model of the land surface. The resultant model was examined to identify historic and natural features and georeferenced with aerial photographs (the earliest of which dates to 1918); this provided us with data concerning the landscape before mechanized farming and other modern surface-changing events took place. \nThe Jezreel team then conducted an intensive landscape survey of greater Jezreel for three weeks in June 2012. The main goal of the inaugural season was to record surface features in a three square kilometer area to the west, north, and east of Tel Jezreel in order to identify areas for excavation in summer 2013. The Jezreel team documented more than 360 features, including cisterns, cave tombs, rock-cut tombs, agricultural and industrial installations, terrace and village walls, quarries and more; most of these features had never been systematically recorded before. The results of this survey shed light on the extent of different settlements at Jezreel from late prehistory through to the 20th century CE Palestinian village of Zer’in.','Co-directors: Norma Franklin and Jennie Ebeling\nSenior Field Staff: Deborah Appler, Julye Bidmead, Noga Blockman and Ian Cipin\nSurvey Participants: Megan Anderson, Nathan Biondi, Sarah Carlton, Emma Dunleavy, Kelly Goodner, Michael Koletsos, Emily Mella, Hilda Torres (University of Evansville); John Egerton, Deborah Graf, Rebekah Thomas (Moravian Theological Seminary); Jeff Anderson (Wayland Baptist University); Willie Ondricek (University of the Holy Land); and Daria Trumbo\nTechnology Specialists: Peter Ostrin and Matthew Bradley'),
('3','Three areas - Area S, M, and K - were chosen for excavation during the inaugural excavation season of the Jezreel Expedition for four weeks in May-June 2013. Excavation squares were opened in Area S East in an area where several \"platforms\" were identified in the aerial LiDAR. An exposed complex of features on a bedrock promontory was explored in Area M on the northern edge of Tel Jezreel. In addition, a large winery complex with a treading floor, two vats, and other rock-cut features in Area K, located at the base of the slope northeast of Tel Jezreel at the edge of the agricultural terrace (Area T). A brief season was also conducted in December to explore a square building in Area P within sight of Ain Jalut (Ein Harod) to the east in the valley below.','Co-directors: Norma Franklin and Jennie Ebeling\nSenior Field Staff: Deborah Appler, Julye Bidmead, Noga Blockman, Ian Cipin, and Philippe Guillaume\nRegistrars: Judith Hadley and Kelly Goodner\nTechnology Specialists: Peter Ostrin and Matthew Bradley\nPrehistory Specialist: Estelle Orrelle\nSquare Supervisors: Nate Biondi, Geoffrey Cowling, Katherine Crawford, Michael Koletsos, Marilyn Love, Arthur Stefanski, and Hilda Torres'),
('4','The primary excavation area for the four-week field season in May-June 2014 was Area S. In addition, a MBIIC shaft tomb was excavated in Area K and several trenches were opened in Area P to explore the series of paths that connected Tel Jezreel with the spring below from the Roman period through the modern period.','Co-directors: Norma Franklin and Jennie Ebeling\nSenior Area Supervisor: Ian Cipin\nArea Supervisors: Julye Bidmead, Philippe Guillaume, and Rafi Lewis\nRegistrar: Judith Hadley\nTechnology Specialists: Peter Ostrin and Matthew Bradley\nPrehistory Specialist: Estelle Orrelle\nField School Teaching Assistant: Michael Koletsos\nAssistant Supervisors: Geoffrey Cowling, Morgan Davidson, Kelly Goodner, Michael Koletsos, Michael Sullivan, and Hilda Torres'),
('5','Area S was the primary excavation area in our four-week field season in May-June 2018. In addition, we opened a probe at the base of the cliff near the shaft tomb excavated in 2014 in Area K.','Co-directors: Norma Franklin and Jennie Ebeling\nField Director: Ian Cipin\nArea Supervisors:  Deborah Appler, Julye Bidmead, Noga Blockman, Philippe Guillaume, Michael Koletsos\nRegistrar: Ann Stehney \nEducation Coordinator: Julye Bidmead\nTechnology Specialists: Peter Ostrin and Matthew Bradley\nPrehistory Specialist: Estelle Orrelle\nArchitectural Surveyor: Alexander (Sasha) Pechuro\nSquare Supervisors: Andrea Creel, Morgan Davidson, Marilyn Love, Katie Mickus, Yolanda Norton, Emily Stewart, Michael Sullivan, Matthew Susnow'),
('6','For four weeks in May-June 2016, the Jezreel Expedition team continued excavating in the main excavation area on Tel \'Ein Jezreel (Area S). In addition, a trench was opened in Area L to explore the road leading from the valley to the Iron Age gate on the south side of Tel Jezreel and a shaft tomb complex and olive press were explored in Area Q.','Co-directors: Norma Franklin and Jennie Ebeling\nField Director: Ian Cipin\nArea Supervisors:  Deborah Appler, Noga Blockman, Philippe Guillaume, Inbal Samet \nRegistrar: Ann Stehney \nEducation Coordinator: Andrea Creel\nTechnology Specialists: Peter Ostrin and Matthew Bradley\nPrehistory Specialist: Estelle Orrelle\nArchitectural Surveyor: Alexander (Sasha) Pechuro\nSquare Supervisors: Andrea Creel, Morgan Davidson, Elizabeth Kunz, Katie Mickus, Ashley Motes, Tim Smith, Emily Stewart, Michael Sullivan, Matthew Susnow'),
('7','Excavations continued in Area S for four weeks in May-June 2017.','Co-directors: Norma Franklin and Jennie Ebeling\nField Director: Ian Cipin \nArea Supervisors: Noga Blockman, Philippe Guillaume, Inbal Samet\nAssistant Area Supervisors: Morgan Davidson and Katie Mickus\nRegistrar: Ann Stehney\nTechnology Specialists: Peter Ostrin and Matthew Bradley\nArchitectural Surveyor: Alexander (Sasha) Pechuro\nSquare Supervisors: Anna Ahrens, Emily Corrigan, Madie Mettler, Isaac Rainey, Aleksandra Rodzinka, Tim Smith, Rebecca Webb'),
('8','Excavations continued in Area S for the final field season of the Jezreel Expedition for four weeks in May-June 2018.','Co-directors: Norma Franklin and Jennie Ebeling\nField Director: Ian Cipin\nArea Supervisors: Noga Blockman, Philippe Guillaume, Inbal Samet\nAssistant Area Supervisors: Morgan Davidson, Katie Mickus, Aleksandra Rodzinka, Tim Smith, Matthew Susnow\nAssistant to the Field Director: Isaac Rainey \nRegistrar: Ann Stehney\nTechnology Specialists: Peter Ostrin and Matthew Bradley\nArchitectural Surveyor: Alexander (Sasha) Pechuro');

